<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="LoginForm.cs">
        <SubType>Form</SubType>
      </Compile>
        
            <ProjectReference Include="..\BasketModel\BasketModel.csproj" />
            <ProjectReference Include="..\BasketPersistence\BasketPersistence.csproj" />
            <ProjectReference Include="..\BasketServices\BasketServices.csproj" />
            <ProjectReference Include="..\BasketServer\BasketServer.csproj" />
            <ProjectReference Include="..\BasketNetworking\BasketNetworking.csproj" />
            <Compile Update="MainMenuForm.cs">
              <SubType>Form</SubType>
            </Compile>
            <Compile Update="SignUpForm.cs">
              <SubType>Form</SubType>
            </Compile>
            <Compile Update="PurchaseForm.cs">
              <SubType>Form</SubType>
            </Compile>
            <Compile Remove="UserEventArgs.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="client.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
