<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\BasketPersistence\BasketPersistence.csproj" />
        <ProjectReference Include="..\BasketServices\BasketServices.csproj" />
        <ProjectReference Include="..\BasketModel\BasketModel.csproj" />
        <ProjectReference Include="..\BasketNetworking\BasketNetworking.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Protobuf Include="proto\Service.proto" GrpcServices="Server" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.56.0" />
        <PackageReference Include="Google.Protobuf" Version="3.31.0-rc2" />
        <PackageReference Include="Grpc.Tools" Version="2.56.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Grpc.Core" Version="2.46.6" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0-preview.3.25171.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0-preview.3.25171.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.3.25171.5" />
    </ItemGroup>
    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>