plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.13'
    id 'org.beryx.jlink' version '2.25.0'
}
application {
    mainClass = 'ro.mpp2024.Start'
}
group = 'ro.mpp2024'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project (':BasketModel')
    implementation project (':BasketServer')
    implementation project (':BasketServices')
    implementation project (':BasketNetworking')
    implementation project (':BasketPersistence')


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.openjfx:javafx-controls:17.0.12'
    implementation 'org.openjfx:javafx-fxml:17.0.12'
    testImplementation group: 'junit', name: 'junit', version:'4.12'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.14.0'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.14.0'
    implementation group: 'com.google.guava', name:'guava', version:'31.0.1-jre'

    implementation 'org.springframework:spring-context:6.1.5'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    runtimeOnly group: 'org.xerial', name:'sqlite-jdbc', version:'3.34.0'
}

javafx{
    version="17.0.12"
    modules=['javafx.controls', 'javafx.fxml']
}
test {
    useJUnitPlatform()
}
