plugins {
    id 'java'
}

group = 'bonti'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    implementation project (':BasketModel')
    implementation project (':BasketPersistence')
    implementation project (':BasketServices')
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}